name: Testing Github Actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/setup-node
        with:
          node-version: '14.17.0'
      - run: node --v
