name: Testing Github Actions
on: [push]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - run: echo "Sequential job 2"
  print-author:
    runs-on: linux
    steps:
      - run: uname
      - run: ifconfig
