name: Testing Github Actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Checking node installed
        run: node --version
      - name: Installing npm packages
        run: yarn
      - name: Build Project
        run: yarn run build
